apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/COMO-Acacio/k8s-Tests.git  # Must contains the GitHub repo in which the files are stored
    path: Guestbook-PHP-Redis   # Subfolder (if applicable) on the GitHub repo
    targetRevision: minikube
  destination:  
    server: https://kubernetes.default.svc
    namespace: guestbook    # This namespace shall be he same as the app namespace, for connection
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true